<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="6" failed="2" ignored="0" total="17" passed="9">
  <reporter-output>
  </reporter-output>
  <suite name="TestSuite1" duration-ms="96630" started-at="2019-04-23T17:30:24Z" finished-at="2019-04-23T17:32:01Z">
    <groups>
      <group name="secondGroup">
        <method signature="TestTertiary.facebookTest()[pri:0, instance:testNGClasses.TestTertiary@52af6cff]" name="facebookTest" class="testNGClasses.TestTertiary"/>
      </group> <!-- secondGroup -->
      <group name="firstGroup">
        <method signature="TestTertiary.amazoninTest()[pri:0, instance:testNGClasses.TestTertiary@52af6cff]" name="amazoninTest" class="testNGClasses.TestTertiary"/>
        <method signature="TestTertiary.googleTest()[pri:0, instance:testNGClasses.TestTertiary@52af6cff]" name="googleTest" class="testNGClasses.TestTertiary"/>
      </group> <!-- firstGroup -->
    </groups>
    <test name="firstTest" duration-ms="42063" started-at="2019-04-23T17:30:24Z" finished-at="2019-04-23T17:31:06Z">
      <class name="testNGClasses.TestPrimary">
        <test-method status="PASS" signature="driverInitiator()[pri:0, instance:testNGClasses.TestPrimary@64616ca2]" name="driverInitiator" is-config="true" duration-ms="3417" started-at="2019-04-23T17:30:24Z" finished-at="2019-04-23T17:30:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driverInitiator -->
        <test-method status="PASS" signature="googleTest()[pri:49, instance:testNGClasses.TestPrimary@64616ca2]" name="googleTest" duration-ms="3490" started-at="2019-04-23T17:30:28Z" finished-at="2019-04-23T17:30:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- googleTest -->
        <test-method status="PASS" signature="amazoninTest()[pri:50, instance:testNGClasses.TestPrimary@64616ca2]" name="amazoninTest" duration-ms="6964" started-at="2019-04-23T17:30:31Z" finished-at="2019-04-23T17:30:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- amazoninTest -->
        <test-method status="PASS" signature="facebookTest()[pri:51, instance:testNGClasses.TestPrimary@64616ca2]" name="facebookTest" duration-ms="25681" started-at="2019-04-23T17:30:38Z" finished-at="2019-04-23T17:31:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- facebookTest -->
        <test-method status="PASS" signature="driverQuit()[pri:0, instance:testNGClasses.TestPrimary@64616ca2]" name="driverQuit" is-config="true" duration-ms="2481" started-at="2019-04-23T17:31:04Z" finished-at="2019-04-23T17:31:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driverQuit -->
      </class> <!-- testNGClasses.TestPrimary -->
    </test> <!-- firstTest -->
    <test name="secondTest" duration-ms="22232" started-at="2019-04-23T17:31:06Z" finished-at="2019-04-23T17:31:29Z">
      <class name="testNGClasses.TestSecondary">
        <test-method status="PASS" signature="driverInitiator()[pri:0, instance:testNGClasses.TestSecondary@67b6d4ae]" name="driverInitiator" is-config="true" duration-ms="2335" started-at="2019-04-23T17:31:06Z" finished-at="2019-04-23T17:31:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driverInitiator -->
        <test-method status="PASS" signature="googleTest()[pri:0, instance:testNGClasses.TestSecondary@67b6d4ae]" name="googleTest" duration-ms="2872" started-at="2019-04-23T17:31:09Z" finished-at="2019-04-23T17:31:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- googleTest -->
        <test-method status="PASS" signature="facebookTest()[pri:0, instance:testNGClasses.TestSecondary@67b6d4ae]" name="facebookTest" duration-ms="2939" started-at="2019-04-23T17:31:12Z" depends-on-methods="testNGClasses.TestSecondary.googleTest" finished-at="2019-04-23T17:31:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- facebookTest -->
        <test-method status="PASS" signature="amazoninTest()[pri:0, instance:testNGClasses.TestSecondary@67b6d4ae]" name="amazoninTest" duration-ms="11990" started-at="2019-04-23T17:31:15Z" depends-on-methods="testNGClasses.TestSecondary.facebookTest" finished-at="2019-04-23T17:31:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- amazoninTest -->
        <test-method status="PASS" signature="driverQuit()[pri:0, instance:testNGClasses.TestSecondary@67b6d4ae]" name="driverQuit" is-config="true" duration-ms="2085" started-at="2019-04-23T17:31:26Z" finished-at="2019-04-23T17:31:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driverQuit -->
      </class> <!-- testNGClasses.TestSecondary -->
    </test> <!-- secondTest -->
    <test name="thirdTest" duration-ms="17935" started-at="2019-04-23T17:31:29Z" finished-at="2019-04-23T17:31:47Z">
      <class name="testNGClasses.TestTertiary">
        <test-method status="PASS" signature="driverInitiator()[pri:0, instance:testNGClasses.TestTertiary@52af6cff]" name="driverInitiator" is-config="true" duration-ms="2163" started-at="2019-04-23T17:31:29Z" finished-at="2019-04-23T17:31:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driverInitiator -->
        <test-method status="PASS" signature="facebookTest()[pri:0, instance:testNGClasses.TestTertiary@52af6cff]" name="facebookTest" duration-ms="6277" started-at="2019-04-23T17:31:31Z" finished-at="2019-04-23T17:31:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- facebookTest -->
        <test-method status="PASS" signature="googleTest()[pri:0, instance:testNGClasses.TestTertiary@52af6cff]" name="googleTest" duration-ms="670" started-at="2019-04-23T17:31:37Z" finished-at="2019-04-23T17:31:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- googleTest -->
        <test-method status="PASS" signature="amazoninTest()[pri:0, instance:testNGClasses.TestTertiary@52af6cff]" name="amazoninTest" duration-ms="7963" depends-on-groups="secondGroup" started-at="2019-04-23T17:31:38Z" finished-at="2019-04-23T17:31:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- amazoninTest -->
        <test-method status="PASS" signature="driverQuit()[pri:0, instance:testNGClasses.TestTertiary@52af6cff]" name="driverQuit" is-config="true" duration-ms="861" started-at="2019-04-23T17:31:46Z" finished-at="2019-04-23T17:31:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driverQuit -->
      </class> <!-- testNGClasses.TestTertiary -->
    </test> <!-- thirdTest -->
    <test name="failTestInTestAnnotation" duration-ms="7251" started-at="2019-04-23T17:31:47Z" finished-at="2019-04-23T17:31:54Z">
      <class name="testNGClasses.FailTestInTestAnnotation">
        <test-method status="PASS" signature="driverInitiator()[pri:0, instance:testNGClasses.FailTestInTestAnnotation@50f8360d]" name="driverInitiator" is-config="true" duration-ms="2038" started-at="2019-04-23T17:31:47Z" finished-at="2019-04-23T17:31:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driverInitiator -->
        <test-method status="SKIP" signature="googleTest()[pri:49, instance:testNGClasses.FailTestInTestAnnotation@50f8360d]" name="googleTest" duration-ms="3241" started-at="2019-04-23T17:31:49Z" finished-at="2019-04-23T17:31:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [google] but found [Google]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [google] but found [Google]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testNGClasses.FailTestInTestAnnotation.googleTest(FailTestInTestAnnotation.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- googleTest -->
        <test-method status="SKIP" signature="googleTest()[pri:49, instance:testNGClasses.FailTestInTestAnnotation@50f8360d]" name="googleTest" duration-ms="371" started-at="2019-04-23T17:31:52Z" finished-at="2019-04-23T17:31:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [google] but found [Google]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [google] but found [Google]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testNGClasses.FailTestInTestAnnotation.googleTest(FailTestInTestAnnotation.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- googleTest -->
        <test-method status="SKIP" signature="googleTest()[pri:49, instance:testNGClasses.FailTestInTestAnnotation@50f8360d]" name="googleTest" duration-ms="408" started-at="2019-04-23T17:31:52Z" finished-at="2019-04-23T17:31:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [google] but found [Google]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [google] but found [Google]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testNGClasses.FailTestInTestAnnotation.googleTest(FailTestInTestAnnotation.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- googleTest -->
        <test-method status="FAIL" signature="googleTest()[pri:49, instance:testNGClasses.FailTestInTestAnnotation@50f8360d]" name="googleTest" duration-ms="374" started-at="2019-04-23T17:31:53Z" finished-at="2019-04-23T17:31:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [google] but found [Google]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [google] but found [Google]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testNGClasses.FailTestInTestAnnotation.googleTest(FailTestInTestAnnotation.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- googleTest -->
        <test-method status="PASS" signature="driverQuit()[pri:0, instance:testNGClasses.FailTestInTestAnnotation@50f8360d]" name="driverQuit" is-config="true" duration-ms="807" started-at="2019-04-23T17:31:53Z" finished-at="2019-04-23T17:31:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driverQuit -->
      </class> <!-- testNGClasses.FailTestInTestAnnotation -->
    </test> <!-- failTestInTestAnnotation -->
    <test name="failTestGlobal" duration-ms="6982" started-at="2019-04-23T17:31:54Z" finished-at="2019-04-23T17:32:01Z">
      <class name="testNGClasses.FailTestGlobal">
        <test-method status="PASS" signature="driverInitiator()[pri:0, instance:testNGClasses.FailTestGlobal@153f5a29]" name="driverInitiator" is-config="true" duration-ms="1992" started-at="2019-04-23T17:31:54Z" finished-at="2019-04-23T17:31:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driverInitiator -->
        <test-method status="SKIP" signature="googleTest()[pri:49, instance:testNGClasses.FailTestGlobal@153f5a29]" name="googleTest" duration-ms="3089" started-at="2019-04-23T17:31:56Z" finished-at="2019-04-23T17:31:59Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [google] but found [Google]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [google] but found [Google]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testNGClasses.FailTestGlobal.googleTest(FailTestGlobal.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- googleTest -->
        <test-method status="SKIP" signature="googleTest()[pri:49, instance:testNGClasses.FailTestGlobal@153f5a29]" name="googleTest" duration-ms="348" started-at="2019-04-23T17:31:59Z" finished-at="2019-04-23T17:31:59Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [google] but found [Google]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [google] but found [Google]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testNGClasses.FailTestGlobal.googleTest(FailTestGlobal.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- googleTest -->
        <test-method status="SKIP" signature="googleTest()[pri:49, instance:testNGClasses.FailTestGlobal@153f5a29]" name="googleTest" duration-ms="404" started-at="2019-04-23T17:31:59Z" finished-at="2019-04-23T17:32:00Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [google] but found [Google]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [google] but found [Google]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testNGClasses.FailTestGlobal.googleTest(FailTestGlobal.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- googleTest -->
        <test-method status="FAIL" signature="googleTest()[pri:49, instance:testNGClasses.FailTestGlobal@153f5a29]" name="googleTest" duration-ms="359" started-at="2019-04-23T17:32:00Z" finished-at="2019-04-23T17:32:00Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [google] but found [Google]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [google] but found [Google]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testNGClasses.FailTestGlobal.googleTest(FailTestGlobal.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- googleTest -->
        <test-method status="PASS" signature="driverQuit()[pri:0, instance:testNGClasses.FailTestGlobal@153f5a29]" name="driverQuit" is-config="true" duration-ms="789" started-at="2019-04-23T17:32:00Z" finished-at="2019-04-23T17:32:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driverQuit -->
      </class> <!-- testNGClasses.FailTestGlobal -->
    </test> <!-- failTestGlobal -->
  </suite> <!-- TestSuite1 -->
</testng-results>
